### ISSUE TITLE
Allow for missing comma (like ASI)

### ISSUE THREAD

**Issue by KnisterPeter** [neuroo/json-ast#1]
It would be great if junker will allow to read over missing comma like in this case:

```
{
  "key1": "value1"
  "key2": 1
}
```

**Comment by neuroo** [comment]
It's a good idea. Taking this on. Might take some time before I push this new feature in the junker, don't hesitate if you want to make a pull request though.

**Comment by neuroo** [comment]
Added support for it in 2.1.6
